// 1 - Números pares entre 0 y un máximo

/*var max = parseInt(prompt("Ingrese un maximo"));

let contador = 0
for (let i = 0; i<= max; i++){
    if (i % 2 === 0){
        document.write(i)
    }
}*/


// 3 - Letra por letra

/*let palabra = prompt("Ingresa una palabra ")
document.write("Las letras de la " + palabra + " son:")
for(p of palabra){
    document.write("\n" + p + "\n")
}*/


// 4 - Potencias de 2

/*for (let i = 1; 2**i <= 10000; i++) {
    document.write("\n" + 2**i + "\n")
}*/

// 5 - Mostrar hasta el 5

/*let = 0
for (let i = 0; i <= 10; i++) {
    if (i == 5) break;
    alert(i);
}*/


// 6 - Saltarse el 5

/*let = 0
for (let i = 0; i <= 10; i++) {
    if (i == 5) continue;
    alert(i);
}*/

