// 1- Adición

/*var x = parseInt(prompt ("Ingrese un número"));
var y = parseInt(prompt("Ingrese otro número"));

resultado = (x + y);{
    alert (resultado)
}*/
    


// 2 - Adición  y multiplicación:

/*var x = parseInt(prompt ("Ingrese un número"));
var y = parseInt(prompt("Ingrese otro número"));

resultadoSuma = (x + y); 
resultadoMulti = (x * y);{
    alert (resultadoSuma + "\n" + resultadoMulti)
}*/



// 3 - Promedio

/*var v1 = prompt("Ingrese el primer valor")
var v2 = prompt("Ingrese el segundo valor")
var v3 = prompt("Ingrese el tercer valor")
var v4 = prompt("Ingrese el cuarto valor")
var v5 = prompt("Ingrese el quinto valor")

var promedio = (parseFloat(v1) + parseFloat(v2) + parseFloat(v3) +parseFloat(v4) +parseFloat(v5) /5);
alert ("Su promedio es " + promedio);*/
    



// 4 - Perímetro

/*var base = prompt("Ingrese el primer valor")
var altura = prompt("Ingrese el segundo valor")

var Perímetro = (2 * base) + (2 * altura);
alert ("El perimetro es " +Perímetro)*/



// 5 - Área

/*var base = prompt("Ingrese el primer valor")
var altura = prompt("Ingrese el segundo valor")

var Area = (base * altura) / 2
alert ("El area es " +Area)*/


/* 10 - Contraseña: Pediremos al usuario ingresar usuario y contraseña para ingresar a nuestro sistema. 
Definiremos una contraseña preestablecida. 
Mostrar mensaje con la explicación de si ha ingresado correctamente la contraseña o no.*/

/*var usuario = prompt("Ingrese el usuario")
var contraseña = prompt("Ingrese la contraseña")

if (contraseña == "provi"){
    alert("Welcome");
} else {
    alert ("OW NO OW NO OW NONOO");
}*/