//1 - Valor absoluto

/*var valorAbsoluto = parseInt(prompt("Ingrese un numero")); 

if (valorAbsoluto > 0){
    document.write(valorAbsoluto);
}else if (valorAbsoluto < 0){
    document.write(valorAbsoluto * -1);
}else if (valorAbsoluto == 0){
    document.write(valorAbsoluto);
}else{
    document.write ("NaN");
}*/




// 2 - El mayor

/*var x = prompt("Ingrese el primer numero");
var y = prompt("Ingrese el segundo numero");
if(x === y)
    alert("Son iguales");
if(x > y)
    alert("El numero mayor es : "+x);
if(y > x)
    alert("El numero mayor es : "+y);*/




// 3 - Etapas de la vida

/*var etapa = parseInt (prompt("Ingrese un número"));

if (etapa > 0 && etapa < 2) {
    alert("Estas en la etapa BEBÉ");
} else if (etapa >= 3 && etapa <= 10) {
    alert ("Estas en la etapa NIÑO/NIÑA");
} else if (etapa >=11 && etapa <=14) {
    alert ("Estas pasando por la PREADOLESCENCIA");
} else if (etapa >=15 && etapa <20){
    alert ("Eres un ADOLESCENTE")
}  else if (etapa >=20 && etapa <=25){
    alert ("Eres un JOVEN ADULTO")
}  else if (etapa >25 && etapa <=60){
    alert ("Eres un ADULTO")
}  else if (etapa >60 && etapa <=75){
    alert ("Eres un JUBILADO")
}  else if (etapa >75){
    alert ("Eres un ADULTO MAYOR")
}*/ 



// 4 - Socio del club

/*var edad = parseInt(prompt("Ingresa tu edad"));
var carneDeSocio = prompt("¿Tienes el carnet de socio al dia?");

if (edad > 25 && carneDeSocio != true){
    alert("Puede votar");
}else{
    alert ("No puede votar");
}*/



// 6 - Día de la semana

/*var diaDeLaSemana = parseInt(prompt("Ingrese un numero del 1 al 7 "))
if (diaDeLaSemana > 7){
    alert("Ese número no es válido")
}
switch (diaDeLaSemana){
    case 1:
        document.write("Es Lunes");
        break;
    case 2:
        document.write("Es Martes");
        break;
    case 3:
        document.write("Es Miercoles");
        break;
    case 4:
        document.write("Es Jueves");
        break;
    case 5:
        document.write("Es Viernes");
        break;
    case 6:
        document.write("Es Sabado");
        break;
    case 7:
        document.write("Es Domingo");
        break;
    }*/

